export const ammoIcons: Record<string, string> = {
    '.223 FMJ': '/images/ammo/223fmj.gif',
    '.44 Magnum FMJ': '/images/ammo/44fmj.gif',
    '.44 Magnum JHP': '/images/ammo/44jhp.gif',
    '.45 caliber': '/images/ammo/45cal.gif',
    '2mm EC': '/images/ammo/2mmec.gif',
    '4.7mm caseless': '/images/ammo/47mm.gif',
    '5mm AP': '/images/ammo/5mmap.gif',
    '5mm JHP': '/images/ammo/5mmjhp.gif',
    '7.62mm': '/images/ammo/762mm.gif',
    '9mm': '/images/ammo/9mm.gif',
    '9mm ball': '/images/ammo/9mmball.png',
    '10mm AP': '/images/ammo/10mmap.gif',
    '10mm JHP': '/images/ammo/10mmjhp.gif',
    '14mm AP': '/images/ammo/14mmap.gif',
    'BBs': '/images/ammo/bbs.gif',
    '12 gauge shotgun shells': '/images/ammo/12ga.gif',
    'Explosive rocket': '/images/ammo/explosiverocket.gif',
    'Rocket AP': '/images/ammo/rocketap.gif',
    'Flamethrower fuel': '/images/ammo/flamethrowerfuel.gif',
    'Flamethrower fuel Mk II': '/images/ammo/flamethrowerfuel2.gif',
    'HN Needler cartridge': '/images/ammo/needler.png',
    'HN AP Needler cartridge': '/images/ammo/needlerap.png',
    'Microfusion cell': '/images/ammo/mfc.gif',
    'Small energy cell': '/images/ammo/sec.gif',
};
