export const weaponIcons: Record<string, string> = {
    // Pistols
    '.223 pistol': '/images/weapons/223pistol.png',
    '9mm Mauser': '/images/weapons/9mmmauser.png',
    '10mm pistol': '/images/weapons/10mmpistol.png',
    '14mm pistol': '/images/weapons/14mmpistol.png',
    'Desert Eagle .44': '/images/weapons/deserteagle.png',
    'Desert Eagle (exp. mag.)': '/images/weapons/deserteagleexp.png',
    '.44 Magnum revolver': '/images/weapons/44magnumrevolver.png',
    '.44 Magnum (speed load)': '/images/weapons/44magnumspeedload.png',
    'Needler pistol': '/images/weapons/needlerpistol.png',
    'Gauss pistol': '/images/weapons/gausspistol.png',
    'PPK12 Gauss pistol': '/images/weapons/gausspistol.png',
    'Zip gun': '/images/weapons/zipgun.png',
    // SMGs
    '10mm SMG': '/images/weapons/10mmsmg.png',
    'Tommy gun': '/images/weapons/tommygun.gif',
    'M3A1 Grease Gun SMG': '/images/weapons/greasegun.png',
    'H&K P90c': '/images/weapons/hkp90c.png',
    'H&K G11': '/images/weapons/hkg11.png',
    'H&K G11E': '/images/weapons/hkg11e.png',
    'Assault rifle': '/images/weapons/assaultrifle.png',
    XL70E3: '/images/weapons/xl70e3.gif',
    'FN FAL': '/images/weapons/fnfal.png',
    'FN FAL HPFA': '/images/weapons/fnfal.png',
    'FN FAL (night sight)': '/images/weapons/fnfalnightsight.png',
    'Hunting rifle': '/images/weapons/huntingrifle.png',
    'Scoped Hunting rifle': '/images/weapons/scopedhuntingrifle.webp',
    'Pipe rifle': '/images/weapons/piperifle.gif',
    'Red Ryder BB gun': '/images/weapons/redryderbbgun.png',
    'Red Ryder LE BB gun': '/images/weapons/redryderlebb.png',
    'Sniper rifle': '/images/weapons/sniperrifle.png',
    'Gauss rifle': '/images/weapons/gaussrifle.png',
    'M72 Gauss rifle': '/images/weapons/gaussrifle.png',
    'Combat shotgun': '/images/weapons/combatshotgun.png',
    'H&K CAWS': '/images/weapons/hkcaws.png',
    'Pancor Jackhammer': '/images/weapons/pancorjackhammer.png',
    Shotgun: '/images/weapons/shotgun.png',
    'Sawed-off shotgun': '/images/weapons/sawedoffshotgun.png',
    Minigun: '/images/weapons/minigun.png',
    'Avenger minigun': '/images/weapons/avengerminigun.png',
    'Vindicator minigun': '/images/weapons/vindicatorminigun.png',
    'Light support weapon': '/images/weapons/lsw.png',
    Bozar: '/images/weapons/bozar.png',
    M60: '/images/weapons/m60.png',
    Flamer: '/images/weapons/flamer.png',
    'Improved Flamer': '/images/weapons/improvedflamer.webp',
    'Rocket launcher': '/images/weapons/rocketlauncher.png',
    // Energy pistols
    'Alien blaster': '/images/weapons/alienblaster.png',
    'Laser pistol': '/images/weapons/laserpistol.png',
    'Magneto-laser pistol': '/images/weapons/magnetolaserpistol.png',
    'Plasma pistol': '/images/weapons/plasmapistol.png',
    'Plasma pistol (ext. cap.)': '/images/weapons/plasmapistolext.png',
    'Pulse pistol': '/images/weapons/pulsepistol.png',
    'YK32 pulse pistol': '/images/weapons/pulsepistol.png',
    // Energy rifles
    'Gatling laser': '/images/weapons/gatlinglaser.png',
    'Laser rifle': '/images/weapons/laserrifle.png',
    'Laser rifle (ext. cap.)': '/images/weapons/laserrifleext.png',
    'Plasma rifle': '/images/weapons/plasmarifle.png',
    'Turbo plasma rifle': '/images/weapons/turboplasmarifle.png',
    'Pulse rifle': '/images/weapons/pulserifle.png',
    'YK42B pulse rifle': '/images/weapons/pulserifle.png',
};
